### ISSUE TITLE
No more gh-pages

### ISSUE THREAD

**Issue by john-kurkowski** [ForSpareParts/ForSpareParts.github.io#1]
I love this article! http://forspareparts.github.io/2016/01/24/actions-up-data-sideways/ But your whole GitHub Pages site is now a 404. Looks like there's no `gh-pages` branch? Can the internet haz your wisdom again?

**Comment by davidwallacejackson** [comment]
Man, I feel like an idiot. Thanks for leaving this issue, John, I'm sorry I never saw it. I forgot about my blog and it went offline when I changed my github handle.

**Comment by john-kurkowski** [comment]
That makes sense. So, this is closed? Is there a new link?

**Comment by john-kurkowski** [comment]
That makes sense. So, this is closed? Is there a new link? Can you redirect old links?

**Comment by davidwallacejackson** [comment]
Everything is at davidwallacejackson.github.io now, so: http://davidwallacejackson.github.io/2016/01/24/actions-up-data-sideways/

I don't know if it's possible to redirect old links, though...
